export const agentsTemplate = [
  '# AGENTS.md',
  '',
  '本文件用于指导 Codex、Cursor、Claude Code 等编程工具接手当前 Kooboo 项目。',
  '',
  '## 项目定位',
  '',
  '这是一个 Kooboo 远程开发项目，不要把它当成普通 Node.js / Express / 前端项目。',
  '',
  '优先理解目录语义，再决定代码应该放在哪里。',
  '',
  '## 开工前先读什么',
  '',
  '1. 当前项目的 `kooboo.d.ts`',
  '2. 当前项目的目录结构',
  '3. 目标目录附近已经能工作的文件',
  '4. Kooboo 远程开发文档：',
  '   - https://chaobin0701.github.io/kb-document/kooboo-remote/ai-prompts',
  '   - https://chaobin0701.github.io/kb-document/kooboo-remote/ai-remote-dev-notes',
  '   - https://chaobin0701.github.io/kb-document/kooboo-remote/file-structure-overview',
  '',
  '## 工作原则',
  '',
  '- 改动尽量最小',
  '- 优先复用已有模式、已有模块、已有命名',
  '- 保持目录语义不变',
  '- 不要随意改动远端资源目录',
  '- 如果涉及内容系统，先确认是 Label、HTML Block、Content 还是 Commerce 配置',
  '- 如果模块案例库里已有相近方案，优先复用结构和对象边界',
  '',
  '## 命令边界',
  '',
  '- `sync`：自动监听并持续同步',
  '- `push`：批量推送当前工作区资源',
  '- `deploy`：手动指定文件、目录或通配符，精准部署到远程站点',
  '- `pull`：从远端拉回本地',
  '- `clone`：克隆远端站点并生成本地工作区',
  '- `new`：创建新的 Kooboo 站点工作区',
  '',
  '## 目录语义',
  '',
  '下面这些目录都带有 Kooboo 语义，不能按普通文件夹理解：',
  '',
  '- `src/api`',
  '- `src/code`',
  '- `src/layout`',
  '- `src/page`',
  '- `src/view`',
  '- `src/js`',
  '- `src/css`',
  '- `src/module`',
  '',
  '## 修改后请验证',
  '',
  '优先跑：',
  '',
  '```bash',
  'pnpm build',
  '```',
  '',
  '如果改的是命令或 scaffold，检查：',
  '',
  '- 帮助文案是否一致',
  '- README 是否同步',
  '- 是否保留了示例/模板痕迹',
  '',
  '## 最后输出',
  '',
  '完成后请简短说明：',
  '',
  '- 你理解到的目录结构',
  '- 这次改了哪些文件',
  '- 哪些地方最容易写错'
].join('\n')
